# Generated by Django 5.2.8 on 2026-02-12 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("image", models.ImageField(upload_to="carousels/")),
                (
                    "link",
                    models.URLField(blank=True, help_text="Link to a course or page"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "0. Homepage Sliders",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MasterCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("icon_class", models.CharField(default="fa-book", max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "1. Master Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("icon_class", models.CharField(default="fa-file-pdf", max_length=50)),
                ("link", models.URLField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "5. Study Materials",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SuccessStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("exam_name", models.CharField(max_length=100)),
                ("rank", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="success_stories/")),
                ("short_bio", models.TextField()),
            ],
            options={
                "verbose_name_plural": "6. Success Stories",
            },
        ),
        migrations.CreateModel(
            name="YouTubeChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subscribers", models.CharField(max_length=20)),
                ("channel_url", models.URLField()),
            ],
            options={
                "verbose_name_plural": "7. YouTube Channels",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("thumbnail", models.ImageField(upload_to="course_thumbnails/")),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                        ],
                        default="Beginner",
                        max_length=20,
                    ),
                ),
                ("is_live", models.BooleanField(default=False)),
                ("enrollment_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "master_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="courses.mastercategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "2. Courses",
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "3. Modules",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("Video", "Video"),
                            ("PDF", "Notes"),
                            ("Quiz", "Quiz"),
                        ],
                        default="Video",
                        max_length=10,
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="YouTube or Vimeo Link", null=True
                    ),
                ),
                (
                    "content_file",
                    models.FileField(blank=True, null=True, upload_to="lessons/"),
                ),
                (
                    "is_preview",
                    models.BooleanField(
                        default=False, help_text="Check if this is a free demo lesson"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.module",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "4. Lessons",
                "ordering": ["order"],
            },
        ),
    ]
