# Generated by Django 5.2.8 on 2026-02-12 11:59

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_lesson_course_alter_lesson_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="master_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module_categories",
                to="courses.mastercategory",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_lessons",
                to="courses.course",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lesson",
            name="module",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="course",
                chained_model_field="course",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="courses.module",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="course",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_model_field="master_category",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.course",
            ),
        ),
    ]
