# Generated by Django 5.2.8 on 2026-02-12 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_module_master_category_alter_lesson_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="master_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="courses.mastercategory",
            ),
        ),
    ]
