# Generated by Django 5.2.8 on 2026-02-12 12:14

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_module_master_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="course",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                chained_field="master_category",
                chained_model_field="master_category",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="master_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_modules",
                to="courses.mastercategory",
            ),
        ),
    ]
