# Generated by Django 5.2.8 on 2026-02-13 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_module_course_alter_module_master_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed information about this video content",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lecturer_name",
            field=models.CharField(
                blank=True, default="Admin", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="master_category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_modules",
                to="courses.mastercategory",
            ),
            preserve_default=False,
        ),
    ]
