# Generated by Django 5.2.8 on 2026-02-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_lesson_description_lesson_lecturer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Upload a specific thumbnail for this lesson video",
                null=True,
                upload_to="lesson_thumbnails/",
            ),
        ),
    ]
