# Generated by Django 5.2.8 on 2026-02-13 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_lesson_thumbnail"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Teacher", "Teacher"),
                            ("Student", "Student"),
                        ],
                        default="Student",
                        max_length=10,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="default_user,png",
                        null=True,
                        upload_to="profile_pics/",
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField(blank=True)),
                (
                    "qualification",
                    models.CharField(
                        blank=True,
                        help_text="e.g. M.Sc in Physics",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("experience_years", models.PositiveIntegerField(default=0)),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Short professional summary"
                    ),
                ),
                (
                    "enrollment_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "subject_specialization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teachers",
                        to="courses.mastercategory",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
