# Generated by Django 5.2.8 on 2026-02-13 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"create_user_profile": "Teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taught_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
