# Generated by Django 5.2.8 on 2026-02-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, default="default_user.png", null=True, upload_to="profiles/"
            ),
        ),
    ]
