# Generated by Django 5.2.8 on 2026-02-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0015_alter_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Summary or written notes for this lesson",
                null=True,
            ),
        ),
    ]
