# Generated by Django 5.2.8 on 2026-02-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0016_lesson_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="notes",
        ),
        migrations.AddField(
            model_name="lesson",
            name="notes_file",
            field=models.FileField(
                blank=True,
                help_text="Upload PDF Notes for this lesson",
                null=True,
                upload_to="lesson_notes/",
            ),
        ),
    ]
