# Generated by Django 5.2.8 on 2026-02-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0017_remove_lesson_notes_lesson_notes_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="enrollment_count",
        ),
    ]
