# Generated by Django 5.2.8 on 2026-02-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_remove_course_enrollment_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False,
                        help_text="Check this once you have replied to the student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "8. Contact Messages",
            },
        ),
    ]
