# Generated by Django 5.2.8 on 2026-02-20 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0019_contactmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to=models.Q(("profile__user_type", "Student")),
                related_name="enrolled_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
