# Generated by Django 5.2.8 on 2026-02-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0020_alter_course_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="branch",
            field=models.CharField(
                blank=True, help_text="e.g. Computer Science", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="college_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
