# Generated by Django 5.2.8 on 2026-02-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0021_profile_branch_profile_college_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                default="Male",
                max_length=10,
            ),
        ),
    ]
