# Generated by Django 5.2.8 on 2026-02-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0022_profile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this teacher can upload courses.",
            ),
        ),
    ]
