# Generated by Django 5.2.8 on 2026-02-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0023_profile_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
    ]
