# Generated by Django 5.2.8 on 2026-03-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0027_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlessonprogress",
            name="last_position",
            field=models.FloatField(default=0.0),
        ),
    ]
