# Generated by Django 5.2.8 on 2026-03-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0028_userlessonprogress_last_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="resources",
            field=models.TextField(
                blank=True,
                help_text="Add links or descriptions of resources here (e.g. GitHub link, useful websites)",
                null=True,
            ),
        ),
    ]
