# Generated by Django 5.2.8 on 2026-03-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0029_lesson_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fcm_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
