# Generated by Django 5.2.8 on 2026-03-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0030_profile_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="auth_provider",
            field=models.CharField(default="email", max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
